### ISSUE TITLE
在 VSCode 中用 Markdown 做「数字化」学习笔记 | OrangeX4's Blog

### ISSUE THREAD

**Issue by OrangeX4** [OrangeX4/gitalk#24]
https://blog.orangex4.cool/post/notes-in-markdown/ 

 教程向: 在 VSCode 中用 Markdown 做「数字化」学习笔记        VSCode 配上 Markdown 语言, 就能写出酷炫, 便捷, 且适应互联网的「数字化」学习笔记.                  这个教程是我这段时间踩过各种各样的坑之后, 总结 VSCode 做学习笔记的最佳实践. 如果你对在 VSCode 中做笔记有什么好的主意, 欢迎留下你

**Comment by aqlkzf** [comment]
请问可以详细叙述下snips的用法吗？  
我在使用 \\p22matrix 时 输入\\p22就变为了p_{22}

**Comment by OrangeX4** [comment]
啊，抱歉，因为我已经删掉 vscode 原生的 snippets 了，你也可以试着切换到 hypersnips，按照我的配置的话，你可以用 pmat2 来代替 \p22matrx

**Comment by OrangeX4** [comment]
啊，抱歉，因为我已经删掉 vscode 原生的 snippets 了，你也可以试着切换到 hypersnips，按照我的配置的话，你可以用 pmat2 来代替 \p22matrx

**Comment by aqlkzf** [comment]
还有输入其他的一些 比如 \\-1 ⇒ ^{-1} 没有反应 ，输入\\bracket  还未输完就自动补未向量b了   ，请问我需要怎样配置才能达到一样的效果？ 谢谢

**Comment by aqlkzf** [comment]
请问能否给出一份详细的snippets使用说明，或者给一个有类似使用方法的说明文档地址，最近用的比较急，谢谢！

**Comment by OrangeX4** [comment]
如果你比较急的话，可以把那个 hypersnips for math 插件卸载掉，这样就不会触发这些效果了，这就就可以用着旧的 snippets

**Comment by FarSightHunter** [comment]
受益匪浅，太感谢LZ了

**Comment by OrangeX4** [comment]
> @FarSightHunter
> 受益匪浅，太感谢LZ了

好耶！能帮上忙就好

**Comment by Zxy-9** [comment]
想问问在线浏览文档的时候一直显示加载中是怎么回事呀

**Comment by OrangeX4** [comment]
> 想问问在线浏览文档的时候一直显示加载中是怎么回事呀

是网络问题。在 github 上的笔记要挂代理才能查看。

**Comment by WhyLIM** [comment]
您好，请问Better Markdown & Latex Shortcuts 中的, 快捷键 Shift + Ctrl + Alt + V 上传到的图床可以自定义吗

**Comment by OrangeX4** [comment]
抱歉，暂时还没加自定义图床的功能，你可以去看看其他插件，应该有很多图床相关插件

**Comment by WhyLIM** [comment]
> @OrangeX4
> 抱歉，暂时还没加自定义图床的功能，你可以去看看其他插件，应该有很多图床相关插件

好的，谢谢您！大佬太强了😶

**Comment by animerqi** [comment]
大佬的HyperSnips for Math配置文件代码代码小白表示一脸懵逼，不太清楚有啥功能，大佬可以写一篇文章介绍一下嘛

**Comment by OrangeX4** [comment]
> 大佬的HyperSnips for Math配置文件代码代码小白表示一脸懵逼，不太清楚有啥功能，大佬可以写一篇文章介绍一下嘛

抱歉, 那个配置文件里面的内容比较多, 单独写一篇文章工作量太大了.

其实你可以去看看 hsnips 的语法, 只要你理解了语法, 就能很简单地看懂那个配置文件了

**Comment by f504512764** [comment]
博主，请教一个问题，就是我想导出带左侧目录的html格式，该怎么操作呀？望回复，谢谢

**Comment by OrangeX4** [comment]
> 博主，请教一个问题，就是我想导出带左侧目录的html格式，该怎么操作呀？望回复，谢谢

Markdown 就是 Markdown 文件, 你这种带左侧目录的 html 格式我不太理解是什么意思

**Comment by baitwo02** [comment]
大佬能问一下django实现的博客，有什么比较好的支持markdown语法的富文本编辑器推荐呢？因为想支持直接前端编辑，所以试了很多都有bug
然后能请教一下大佬，你的这个右边的目录功能是怎么实现的吗？
