### ISSUE TITLE
为 Hexo 博客中的 Markdown 添加卡片式链接支持 | OrangeX4's Blog

### ISSUE THREAD

**Issue by OrangeX4** [OrangeX4/gitalk#34]
https://blog.orangex4.cool/post/hexo-link-card/ 

 为 Hexo 博客中的 Markdown 添加卡片式链接支持        我写了一个 Hexo 插件，可以使用现有 Markdown 语法将链接转换为卡片式链接（网页卡片）. 这个插件的 GitHub 地址在这里： OrangeX4/hexo-link-card - GitHubhttps://github.com/OrangeX4/hexo-link-card 卡片式链接

**Comment by lete114** [comment]
可以试试这个 [Lete114/CardLink](https://github.com/Lete114/CardLink)😁
